# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Projects\AntiZTools\ui\aowForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_aowForm(object):
    def setupUi(self, aowForm):
        aowForm.setObjectName("aowForm")
        aowForm.resize(277, 108)
        self.label = QtWidgets.QLabel(aowForm)
        self.label.setGeometry(QtCore.QRect(70, 10, 140, 25))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.aow1Btn = QtWidgets.QPushButton(aowForm)
        self.aow1Btn.setGeometry(QtCore.QRect(10, 47, 75, 23))
        self.aow1Btn.setObjectName("aow1Btn")
        self.aow2Btn = QtWidgets.QPushButton(aowForm)
        self.aow2Btn.setGeometry(QtCore.QRect(100, 47, 75, 23))
        self.aow2Btn.setObjectName("aow2Btn")
        self.aow3Btn = QtWidgets.QPushButton(aowForm)
        self.aow3Btn.setGeometry(QtCore.QRect(190, 47, 75, 23))
        self.aow3Btn.setObjectName("aow3Btn")
        self.stopBtn = QtWidgets.QPushButton(aowForm)
        self.stopBtn.setGeometry(QtCore.QRect(10, 77, 255, 23))
        self.stopBtn.setObjectName("stopBtn")

        self.retranslateUi(aowForm)
        QtCore.QMetaObject.connectSlotsByName(aowForm)

    def retranslateUi(self, aowForm):
        _translate = QtCore.QCoreApplication.translate
        aowForm.setWindowTitle(_translate("aowForm", "窗口的艺术"))
        self.label.setText(_translate("aowForm", "窗口的艺术"))
        self.aow1Btn.setText(_translate("aowForm", "窗口抖动"))
        self.aow2Btn.setText(_translate("aowForm", "窗口飘动"))
        self.aow3Btn.setText(_translate("aowForm", "大小变换"))
        self.stopBtn.setText(_translate("aowForm", "紧急停止"))
