# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Projects\AntiZTools\azt\ui\design\eulaForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_eulaForm(object):
    def setupUi(self, eulaForm):
        eulaForm.setObjectName("eulaForm")
        eulaForm.resize(499, 351)
        self.textBrowser = QtWidgets.QTextBrowser(eulaForm)
        self.textBrowser.setGeometry(QtCore.QRect(-1, -1, 500, 320))
        self.textBrowser.setObjectName("textBrowser")
        self.exitBtn = QtWidgets.QPushButton(eulaForm)
        self.exitBtn.setGeometry(QtCore.QRect(80, 323, 100, 23))
        self.exitBtn.setObjectName("exitBtn")
        self.agreeBtn = QtWidgets.QPushButton(eulaForm)
        self.agreeBtn.setGeometry(QtCore.QRect(310, 323, 100, 23))
        self.agreeBtn.setObjectName("agreeBtn")

        self.retranslateUi(eulaForm)
        QtCore.QMetaObject.connectSlotsByName(eulaForm)

    def retranslateUi(self, eulaForm):
        _translate = QtCore.QCoreApplication.translate
        eulaForm.setWindowTitle(_translate("eulaForm", "AntiZTools用户协议"))
        self.exitBtn.setText(_translate("eulaForm", "退出"))
        self.agreeBtn.setText(_translate("eulaForm", "同意"))
