# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Projects\AntiZTools\ui\debugForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_debugForm(object):
    def setupUi(self, debugForm):
        debugForm.setObjectName("debugForm")
        debugForm.resize(284, 61)
        self.label = QtWidgets.QLabel(debugForm)
        self.label.setGeometry(QtCore.QRect(10, 10, 90, 12))
        self.label.setObjectName("label")
        self.closeBtn = QtWidgets.QPushButton(debugForm)
        self.closeBtn.setGeometry(QtCore.QRect(10, 30, 75, 23))
        self.closeBtn.setObjectName("closeBtn")
        self.titletext = QtWidgets.QTextBrowser(debugForm)
        self.titletext.setGeometry(QtCore.QRect(89, 6, 190, 49))
        self.titletext.setObjectName("titletext")

        self.retranslateUi(debugForm)
        QtCore.QMetaObject.connectSlotsByName(debugForm)

    def retranslateUi(self, debugForm):
        _translate = QtCore.QCoreApplication.translate
        debugForm.setWindowTitle(_translate("debugForm", "debugForm"))
        self.label.setText(_translate("debugForm", "当前窗口标题："))
        self.closeBtn.setText(_translate("debugForm", "关闭"))
