# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\HackTools\ui\password.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PasswordDialog(object):
    def setupUi(self, PasswordDialog):
        PasswordDialog.setObjectName("PasswordDialog")
        PasswordDialog.resize(335, 63)
        self.passwordInput = QtWidgets.QLineEdit(PasswordDialog)
        self.passwordInput.setGeometry(QtCore.QRect(100, 20, 113, 20))
        self.passwordInput.setObjectName("passwordInput")
        self.label = QtWidgets.QLabel(PasswordDialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 70, 12))
        self.label.setObjectName("label")
        self.confirmBtn = QtWidgets.QPushButton(PasswordDialog)
        self.confirmBtn.setGeometry(QtCore.QRect(240, 20, 75, 23))
        self.confirmBtn.setObjectName("confirmBtn")
        self.label_2 = QtWidgets.QLabel(PasswordDialog)
        self.label_2.setGeometry(QtCore.QRect(100, 40, 220, 12))
        self.label_2.setStyleSheet("color: red")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(PasswordDialog)
        QtCore.QMetaObject.connectSlotsByName(PasswordDialog)

    def retranslateUi(self, PasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        PasswordDialog.setWindowTitle(_translate("PasswordDialog", "请输入密码"))
        self.label.setText(_translate("PasswordDialog", "请输入密码："))
        self.confirmBtn.setText(_translate("PasswordDialog", "确认"))
        self.label_2.setText(_translate("PasswordDialog", "密码错误，请重试"))
