# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\HackTools\ui\ZBDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ZBDialog(object):
    def setupUi(self, ZBDialog):
        ZBDialog.setObjectName("ZBDialog")
        ZBDialog.resize(403, 146)
        self.label = QtWidgets.QLabel(ZBDialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 340, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(ZBDialog)
        QtCore.QMetaObject.connectSlotsByName(ZBDialog)

    def retranslateUi(self, ZBDialog):
        _translate = QtCore.QCoreApplication.translate
        ZBDialog.setWindowTitle(_translate("ZBDialog", "ZBMsgDialog"))
        self.label.setText(_translate("ZBDialog", "TextLabel"))
